import { Button, VerticalBox , GroupBox, HorizontalBox, TextEdit, LineEdit, ScrollView, SpinBox} from "std-widgets.slint";

export struct Serial {
    min: int,
    max: int,
}

export component AppWindow inherits Window {
    title: "口算生成工具";
    max-width: 1000px;
    max-height: 800px;
    preferred-width: 1000px;
    preferred-height: 800px;

    in-out property <string> start_date;
    in-out property <string> end_date;

    in-out property <int> common_total: 20;
    in-out property <int> common_min: 0;
    in-out property <int> common_max: 10;

    in-out property <int> carry_total: 20;
    in-out property <int> carry_min_1: 11;
    in-out property <int> carry_max_1: 19;
    in-out property <int> carry_min_2: 1;
    in-out property <int> carry_max_2: 9;

    in-out property <int> serial_total: 20;
    in-out property <int> serial_num: 3;
    in-out property <int> serial_limit: 20;

    in-out property <[Serial]> serials: [];

    in-out property <string> notify;

    in-out property <bool> btn_enabled: true;

    callback generate();
    callback serial_num_changed(int);

    ScrollView { 
        VerticalBox {
            
            GroupBox { 
                title: "基础设置";
                HorizontalBox { 
                    Text {vertical-alignment: center;text: "作业时间";}
                    LineEdit { text: root.start_date; edited(text) => {root.start_date = text;} }
                    Text {vertical-alignment: center;text: "-";}
                    LineEdit { text: root.end_date; edited(text) => {root.end_date = text;} }
                }
            }
            
            GroupBox {
                title: "普通加减";
                HorizontalBox { 
                    Text {
                        vertical-alignment: center;
                        text: "共";
                    }
                    LineEdit {text: root.common_total; edited(text) => {root.common_total = text.to-float();}}
                    Text {vertical-alignment: center; text: "道 从";}
                    LineEdit {text: root.common_min; edited(text) => {root.common_min = text.to-float();}}
                    Text {vertical-alignment: center; text: "到";}
                    LineEdit {text: root.common_max; edited(text) => {root.common_max = text.to-float();}}
                }
            }

            GroupBox {
                title: "进位加法";
                VerticalBox {
                    HorizontalBox {
                        Text {vertical-alignment: center; text: "共";}
                        LineEdit {text: root.carry_total; edited(text) => {root.carry_total = text.to-float();}}
                        Text {vertical-alignment: center; text: "道";}
                    }
                    HorizontalBox { 
                        Text {vertical-alignment: center; text: "加数一从";}
                        LineEdit {text: root.carry_min_1; edited(text) => {root.carry_min_1 = text.to-float();}}
                        Text {vertical-alignment: center; text: "到";}
                        LineEdit {text: root.carry_max_1; edited(text) => {root.carry_max_1 = text.to-float();}}
                    }
                    HorizontalBox { 
                        Text {vertical-alignment: center; text: "加数二从";}
                        LineEdit {text: root.carry_min_2; edited(text) => {root.carry_min_2 = text.to-float();}}
                        Text {vertical-alignment: center; text: "到";}
                        LineEdit {text: root.carry_max_2; edited(text) => {root.carry_max_2 = text.to-float();}}
                    }
                }
            }

            GroupBox {
                title: "连加连减";
                serial_box := VerticalBox {
                    HorizontalBox {
                        Text {vertical-alignment: center; text: "共";}
                        LineEdit {text: root.serial_total; edited(text) => {root.serial_total = text.to-float();}}
                        Text {vertical-alignment: center; text: "道";}
                        SpinBox {value: root.serial_num; edited => {root.serial_num_changed(self.value)}}
                        Text {vertical-alignment: center; text: "位数字 结果不超过";}
                        LineEdit {text: root.serial_limit; edited(text) => {root.serial_limit = text.to-float();}}
                    }

                    for serial[index] in root.serials: HorizontalBox {
                        Text {vertical-alignment: center; text: "第" + (index + 1) + "个数字从";}
                        LineEdit {text: serial.min; edited(text) => {serial.min = text.to-float();}}
                        Text {vertical-alignment: center; text: "到";}
                        LineEdit {text: serial.max; edited(text) => {serial.max = text.to-float();}}
                    }
                }
            }

            Text {vertical-alignment: center; horizontal-alignment: center; text: notify;}

            btn := Button {
                text: "生成";
                max-height: 50px;
                clicked => {generate();}
                enabled: btn_enabled;
            }
        }
    }
}
